"""Real-origin installed-package rollback, XML relations and 1,000-document UI probe."""
from pathlib import Path
import json,os,subprocess,time,urllib.request
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[2];URL='http://127.0.0.1:4178/'
def run():
 server=subprocess.Popen(['python','scripts/serve_static.py','--directory','preview','--port','4178'],cwd=ROOT)
 try:
  for _ in range(100):
   try:urllib.request.urlopen(URL,timeout=1).close();break
   except Exception:time.sleep(.1)
  with sync_playwright() as p:
   exe=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium');browser=p.chromium.launch(executable_path=exe if Path(exe).exists() else None,args=['--no-sandbox']);page=browser.new_page();page.goto(URL)
   packages=page.evaluate('''async()=>{const {ModelStore}=await import('/app/nextmedtator/model-store.mjs');const {fingerprint,sha256}=await import('/app/nextmedtator/integrity.mjs');const store=new ModelStore(),files=new Map([['graph.onnx',new Uint8Array([1])],['fixture.json',new Uint8Array([2])]]);const manifest={format:'nextmedtator-model-v1',id:'storage-fixture',version:'1',runtime:'onnxruntime-web',runtimeVersion:'1.23.2',lineage:{base:{model:'storage-only-fixture',revision:'a'.repeat(40)}},license:{id:'Apache-2.0',notice:'Storage fixture, not executable inference'},files:await Promise.all([...files].map(async([path,bytes])=>({path,bytes:bytes.length,sha256:await sha256(bytes),role:path.endsWith('.onnx')?'graph':'fixture'}))),variants:[{id:'wasm',backend:'wasm',precision:'fp32',codec:'tensor-conformance-v1',graph:'graph.onnx',fixtures:['fixture.json']}],capabilities:[]};const first={manifest,manifestHash:await fingerprint(manifest),files};await store.install(first);const nextManifest={...manifest,version:'2'},next={manifest:nextManifest,manifestHash:await fingerprint(nextManifest),files};const cancelled=new AbortController();cancelled.abort();let stopped=false;try{await store.install(next,{signal:cancelled.signal});}catch{stopped=true;}const original=IDBObjectStore.prototype.put;let failed=false;IDBObjectStore.prototype.put=function(){throw new DOMException('Quota','QuotaExceededError');};try{await store.install(next);}catch{failed=true;}finally{IDBObjectStore.prototype.put=original;}if(!stopped||!failed||(await store.list()).length!==1)throw Error('Atomic installation violated');await store.install(next);await store.remove(next.manifestHash);const rollback=await store.read(first.manifestHash);return {cancelled:stopped,quotaAtomic:failed,rollback:rollback.manifest.version==='1'};}''')
   relations=page.evaluate('''async()=>{const {importMedTator,exportMedTator}=await import('/app/nextmedtator/interchange.mjs');const xml='<N><TEXT>Drug condition</TEXT><TAGS><DRUG id="a" spans="0~4" text="Drug"/><CONDITION id="b" spans="5~14" text="condition"/><TREATS id="r" arg0="a" arg1="b"/></TAGS></N>';const {project}=await importMedTator(xml);const data=project.current;const encoded=exportMedTator(data.documents[0],data.draft.records,data.schema);const again=await importMedTator(encoded.xml);if(JSON.stringify(again.project.current.draft.records[0].relations)!==JSON.stringify(data.draft.records[0].relations))throw Error('Lost relation');return true;}''')
   perf=page.evaluate('''async()=>{const {ReviewProject}=await import('/app/nextmedtator/project.mjs');const {sourceDocument}=await import('/app/nextmedtator/integrity.mjs');const {DEMO_SCHEMA}=await import('/app/nextmedtator/contracts.mjs');const w=document.querySelector('nextmedtator-workspace').workspace;const docs=await Promise.all(Array.from({length:1000},(_,i)=>sourceDocument('doc-'+i,new TextEncoder().encode('The patient denies diabetes.'))));await w.adopt(await ReviewProject.create(docs,DEMO_SCHEMA));w.render();const times=[];for(let i=0;i<30;i++){const start=performance.now();w.root.querySelectorAll('.documents button')[i].click();times.push(performance.now()-start);}times.sort((a,b)=>a-b);const p95=times[Math.floor(times.length*.95)];if(p95>300)throw Error('Document switch exceeds 300ms: '+p95);return {documents:docs.length,switchSamples:times.length,switchP95Ms:p95,heapBytes:performance.memory?.usedJSHeapSize??null,scope:'Cloud Linux Chromium; target laptops not qualified'};}''')
   page.get_by_role('button',name='Privacy & storage',exact=True).click();page.get_by_role('button',name='Pause active timing',exact=True).click();assert page.evaluate('document.querySelector("nextmedtator-workspace").workspace.timer.paused')
   page.get_by_label('Timing idle cutoff in seconds').fill('30');page.get_by_label('Timing idle cutoff in seconds').press('Tab');assert page.evaluate('document.querySelector("nextmedtator-workspace").workspace.timer.idleMs')==30000
   focused=page.evaluate('document.querySelector("nextmedtator-workspace").workspace.root.activeElement!==null');assert focused
   result={'packageStorage':packages,'legacyRelationRoundtrip':relations,'keyboardAndTimingControls':True,'performance':perf};(ROOT/'test-results/parity-edges.json').write_text(json.dumps(result,indent=2));print(json.dumps(result));browser.close()
 finally:server.terminate();server.wait(timeout=5)
if __name__=='__main__':run()
