import {StorageBackend} from './backend/storage-client.mjs';
import {uuid} from './integrity.mjs';
const css=`
:host{display:block;width:100%;font:12px/1.4 system-ui,sans-serif;color:#1d1d1d}
*{box-sizing:border-box}[hidden]{display:none!important}button,input,select{font:inherit;color:inherit}button,select,input{border:1px solid #ccc;background:white;padding:4px;border-radius:2px;max-width:100%}
button{cursor:pointer}button:disabled{opacity:.5;cursor:default}:focus-visible{outline:2px solid #137aab;outline-offset:1px}
.open{width:100%;text-align:left;height:30px;background:#f5f6f7}.panel{height:100%;display:flex;flex-direction:column;min-height:0}
.header{padding:5px;border-bottom:1px solid #ddd;flex-shrink:0;max-height:70%;overflow:auto}.row{display:flex;gap:4px;align-items:center;margin-bottom:4px}.row strong{flex:1}
input{width:100%;min-width:0}select{flex:1;min-width:0}p{margin:4px 0;color:#555}label{display:block}.results{overflow:auto;flex:1;min-height:0;padding:4px}
.hit{display:block;width:100%;text-align:left;border:0;border-bottom:1px dotted #ccc;border-radius:0;padding:6px;background:white;overflow-wrap:anywhere}.hit:hover{background:#f4f9fb}
.name{font-weight:bold;display:block}.count{color:#666;display:block}.snippet{display:block;margin-top:3px}mark{background:#fff3a4;color:inherit}
.pages{display:flex;gap:6px;align-items:center;padding:4px;border-top:1px solid #ddd;flex-shrink:0}.status{overflow-wrap:anywhere}
`;
function el(tag,text,attrs={}){const e=document.createElement(tag);if(text!==null)e.textContent=text;for(const [key,value]of Object.entries(attrs))e.setAttribute(key,value);return e;}
function countLabel(count){return `${count} annotation${count===1?'':'s'}`;}

/** Thin UI adapter. Retrieval never creates tags, predictions or classifications. */
export class CorpusSearch{
    constructor(host,vpp){this.host=host;this.vpp=vpp;this.backend=new StorageBackend({memory:true});this.projectId='live-'+uuid();this.ids=new WeakMap();this.documents=new Map();this.revision=0;this.indexedRevision=-1;this.epoch=0;this.offset=0;this.active=false;this.root=host.attachShadow({mode:'open'});host.search=this;this.build();
        this.unwatch=vpp.$watch(()=>vpp.$data.anns.map(a=>[a._filename,a.text]),()=>{this.revision++;this.indexedRevision=-1;this.epoch++;this.results.replaceChildren();this.offset=0;if(this.active&&this.input.value.trim())this.schedule();},{deep:true});
        this.unwatchCounts=vpp.$watch(()=>vpp.$data.anns.map(a=>a.tags?.length??0),()=>{for(const label of this.results.querySelectorAll('[data-document-id]'))label.textContent=countLabel(this.documents.get(label.dataset.documentId)?.ann.tags?.length??0);});}
    build(){this.root.append(el('style',css));this.open=el('button','Search corpus',{'data-testid':'corpus-search-open',title:'Search the loaded corpus on this device'});this.open.onclick=()=>this.setActive(true);this.root.append(this.open);
        this.panel=el('div',null,{class:'panel'});this.panel.hidden=true;this.root.append(this.panel);const header=el('div',null,{class:'header'}),row=el('div',null,{class:'row'});row.append(el('strong','Corpus search'));const close=el('button','Close',{'data-testid':'corpus-search-close'});close.onclick=()=>this.setActive(false);row.append(close);header.append(row);
        const form=el('form',null);this.input=el('input',null,{type:'search','aria-label':'Search loaded corpus',placeholder:'English words or clinical terms',maxlength:'2000','data-testid':'corpus-search-input'});this.input.oninput=()=>{this.offset=0;this.schedule();};form.append(this.input);
        const options=el('div',null,{class:'row'});this.mode=el('select',null,{'aria-label':'Corpus search mode','data-testid':'corpus-search-mode'});for(const [value,label]of [['words','All words'],['phrase','Exact phrase'],['prefix','Word prefixes'],['advanced','Advanced query']])this.mode.append(el('option',label,{value}));this.mode.onchange=()=>{this.offset=0;this.schedule();};this.go=el('button','Search',{type:'submit','data-testid':'corpus-search-submit'});options.append(this.mode,this.go);form.append(options);form.onsubmit=e=>{e.preventDefault();clearTimeout(this.timer);this.run();};header.append(form);
        header.append(el('p','Find candidate notes; search does not classify or annotate them.'));this.hint=el('p','All words can occur anywhere in the note or filename.');header.append(this.hint);this.status=el('p','Enter a query to search loaded notes.',{class:'status',role:'status','aria-live':'polite','data-testid':'corpus-search-status'});header.append(this.status);this.panel.append(header);
        this.results=el('div',null,{class:'results','aria-label':'Corpus search results'});this.panel.append(this.results);this.pages=el('div',null,{class:'pages'});this.previous=el('button','Previous',{'data-testid':'corpus-search-previous'});this.next=el('button','Next',{'data-testid':'corpus-search-next'});this.previous.onclick=()=>{this.offset-=25;this.run();};this.next.onclick=()=>{this.offset+=25;this.run();};this.range=el('span','');this.pages.append(this.previous,this.range,this.next);this.pages.hidden=true;this.panel.append(this.pages);}
    setActive(active){this.active=active;this.host.dataset.active=String(active);this.host.parentElement.classList.toggle('corpus-search-active',active);this.open.hidden=active;this.panel.hidden=!active;
        if(active){this.input.focus();this.status.textContent=`${this.vpp.$data.anns.length} documents loaded. Enter a query.`;}
        else{this.epoch++;clearTimeout(this.timer);this.backend.close();this.indexing=null;this.indexedRevision=-1;this.documents.clear();this.input.value='';this.offset=0;this.results.replaceChildren();this.pages.hidden=true;}}
    schedule(){this.epoch++;clearTimeout(this.timer);this.results.replaceChildren();this.pages.hidden=true;this.status.textContent=this.input.value.trim()?'Searching…':'Enter a query to search loaded notes.';this.timer=setTimeout(()=>this.run(),300);}
    async ensureIndex(revision){
        if(this.indexing?.revision===revision)return this.indexing.promise;
        const documents=this.vpp.$data.anns.map(ann=>{let id=this.ids.get(ann);if(!id){id=uuid();this.ids.set(ann,id);}return {id,name:ann._filename??'document',text:ann.text??'',ann};});
        const job={revision};job.promise=this.backend.indexCorpus({projectId:this.projectId,revision,documents:documents.map(({ann,...d})=>d)}).then(()=>new Map(documents.map(d=>[d.id,d]))).finally(()=>{if(this.indexing===job)this.indexing=null;});this.indexing=job;return job.promise;
    }
    async run(){const epoch=++this.epoch,revision=this.revision,query=this.input.value,mode=this.mode.value,offset=this.offset;this.hint.textContent={words:'All words can occur anywhere in the note or filename.',phrase:'Words must occur together in this order.',prefix:'Find words beginning with each entered term.',advanced:'Use "quoted phrases", diabet*, and AND / OR / NOT.'}[mode];this.results.replaceChildren();this.pages.hidden=true;
        if(!query.trim()){this.status.textContent='Enter a query to search loaded notes.';return;}this.status.textContent=this.indexedRevision===revision?'Searching…':'Indexing loaded notes in memory…';
        try{if(this.indexedRevision!==revision){const map=await this.ensureIndex(revision);if(epoch!==this.epoch||revision!==this.revision||!this.active)return;this.documents=map;this.indexedRevision=revision;}
            const page=await this.backend.search({projectId:this.projectId,revision,query,mode,offset,limit:25});if(epoch!==this.epoch||revision!==this.revision||!this.active)return;
            this.status.textContent=`${page.total} / ${page.documentCount} documents match`;for(const hit of page.hits){const source=this.documents.get(hit.documentId);if(!source)continue;const button=el('button',null,{class:'hit','data-testid':'corpus-search-hit'});button.append(el('span',hit.name,{class:'name'}),el('span',countLabel(source.ann.tags?.length??0),{class:'count','data-document-id':hit.documentId}));const snippet=el('span',null,{class:'snippet'});for(const part of hit.parts)snippet.append(el(part.match?'mark':'span',part.text));button.append(snippet);button.onclick=()=>{const index=this.vpp.$data.anns.indexOf(source.ann);if(epoch!==this.epoch||index<0||source.ann.text!==source.text||(source.ann._filename??'document')!==source.name){this.schedule();return;}this.vpp.set_ann_idx(index);};this.results.append(button);}
            this.range.textContent=page.total?`${offset+1}–${Math.min(offset+25,page.total)} of ${page.total}`:'0 results';this.previous.disabled=offset===0;this.next.disabled=offset+25>=page.total;this.pages.hidden=page.total<=25;this.results.scrollTop=0;
        }catch(error){if(epoch!==this.epoch||!this.active)return;this.indexedRevision=-1;this.status.textContent=error.code==='SEARCH_QUERY_INVALID'?error.message:'Corpus search is unavailable. Close search to use the original file list; annotations are unchanged.';}}
}
