import { test } from 'node:test';
import assert from 'node:assert/strict';
import { OffsetMap, sourceDocument, fingerprint, clone, jsonParse, canonical, csvCell, sha256 } from '../../src/nextmedtator/integrity.mjs';
import { validateProject, validateRun, DEMO_SCHEMA, validateRecord } from '../../src/nextmedtator/contracts.mjs';
import { ReviewProject, makeRun } from '../../src/nextmedtator/project.mjs';
import { demoProject, authoredSuggestionRun, authoredReference } from '../../src/nextmedtator/samples.mjs';
import { matchRecords, compareSnapshots, categoricalKappa } from '../../src/nextmedtator/compare.mjs';
import { exportBundle, importBundle } from '../../src/nextmedtator/bundle.mjs';
import { zipStore, unzipBounded, crc32, safePath } from '../../src/nextmedtator/zip.mjs';
import { ActiveTimer } from '../../src/nextmedtator/recovery.mjs';
const record = () => ({ id: 'r1', documentId: 'd1', family: 'condition_occurrence', anchor: [{ start: 0, end: 1, text: 'x' }], fields: { concept: 'x' } });
for (const text of ['a\r\nb', '\ufeffhello', '👩‍⚕️ e\u0301', 'ไทย\t<>&"', 'same same'])
    test(`UTF-8 and code-point round trip ${JSON.stringify(text)}`, async () => { const d = await sourceDocument('doc', new TextEncoder().encode(text)); assert.equal(d.text, text); const m = new OffsetMap(text); for (let i = 0; i <= m.length; i++)
        assert.equal(m.toCodePoint(m.toUTF16(i)), i); assert.equal(m.slice(0, m.length), text); });
test('surrogate splits and unpaired surrogates are rejected', () => { assert.throws(() => new OffsetMap('\ud800')); assert.throws(() => new OffsetMap('😀').toCodePoint(1)); });
test('invalid UTF-8 is not silently repaired', async () => { await assert.rejects(sourceDocument('d', new Uint8Array([0xff]))); });
test('unsafe nested JSON keys and oversized/deep JSON are rejected', () => { assert.throws(() => jsonParse('{"a":{"__proto__":1}}')); assert.throws(() => jsonParse(' '.repeat(100), 10)); assert.throws(() => jsonParse('['.repeat(45) + '0' + ']'.repeat(45))); });
test('canonical JSON and source hashes are stable', async () => { assert.equal(await fingerprint({ b: 2, a: 1 }), await fingerprint({ a: 1, b: 2 })); assert.throws(() => canonical({ x: NaN })); assert.notEqual(await sha256('a\r\nb'), await sha256('a\nb')); });
test('CSV formula cells are escaped', () => { assert.equal(csvCell('=SUM(A1)'), `"'=SUM(A1)"`); assert.equal(csvCell(' \t@x'), `"' \t@x"`); });
test('all synthetic families validate', async () => { const p = await demoProject(); for (const d of p.current.documents)
    for (const r of authoredReference(d))
        validateRecord(r, d, p.current.schema); await validateProject(p.current); });
test('accept/edit/reject preserve machine output and completeness is separate', async () => { const p = await demoProject(), d = p.current.documents[0], run = await authoredSuggestionRun(p, d); await p.addRun(run); const original = canonical(p.current.runs[0]); p.review(run.id, run.records[0].id, 'accepted'); assert.equal(p.current.draft.records.length, 1); assert.deepEqual(p.current.draft.completeness, {}); const modified = clone(run.records[0]); modified.fields.experiencer = 'family'; p.review(run.id, run.records[0].id, 'modified', modified); assert.equal(p.current.draft.records.length, 1); p.review(run.id, run.records[0].id, 'rejected', null, 'Wrong experiencer'); assert.equal(p.current.draft.records.length, 0); p.undo(); assert.equal(p.current.draft.records[0].fields.experiencer, 'family'); assert.equal(canonical(p.current.runs[0]), original); });
test('blind mode rejects early inference; frozen human remains unchanged after reveal', async () => { const p = await demoProject('blind'), d = p.current.documents[0], run = await authoredSuggestionRun(p, d); await assert.rejects(p.addRun(run), /Freeze/); assert.throws(() => p.reveal()); p.record(authoredReference(d)[0]); const h = await p.snapshot(); const saved = canonical(h); assert.equal(h.independent, true); assert.throws(() => p.record(authoredReference(d)[1]), /frozen/); await p.addRun(run); assert.equal(p.canSeeMachine, false); p.reveal(); p.review(run.id, run.records[0].id, 'accepted'); assert.equal(canonical(p.current.snapshots[0]), saved); const post = await p.snapshot(); assert.equal(post.independent, false); });
test('prediction coverage cannot masquerade as a complete negative', async () => { const p = await demoProject(), d = p.current.documents[0], r = await makeRun(p, d, [], { producer: { kind: 'imported' }, coverage: [], status: 'complete' }); await assert.rejects(validateRun(r, p.current), /cover/); r.status = 'failed'; await validateRun(r, p.current); });
test('run fingerprint and source identity are checked', async () => { const p = await demoProject(), r = await authoredSuggestionRun(p, p.current.documents[0]); r.settings.threshold = .9; await assert.rejects(p.addRun(r), /fingerprint/); });
test('snapshot tampering is rejected', async () => { const p = await demoProject('blind'); await p.snapshot(); const bad = clone(p.current); bad.snapshots[0].actor = 'another'; await assert.rejects(ReviewProject.open(bad), /hash/); });
test('maximum-cardinality matching does not double count duplicates', () => { const a = record(), b = { ...record(), id: 'r2' }; const m = matchRecords([a], [a, b]); assert.equal(m.pairs.length, 1); assert.equal(m.extra.length, 1); });
test('augmenting paths fix the greedy overlap trap', () => { const a = { ...record(), id: 'a', anchor: [{ start: 0, end: 10 }] }, b = { ...record(), id: 'b', anchor: [{ start: 8, end: 12 }] }, x = { ...record(), id: 'x', anchor: [{ start: 6, end: 12 }] }, y = { ...record(), id: 'y', anchor: [{ start: 0, end: 6 }] }; assert.equal(matchRecords([a, b], [x, y], { mode: 'overlap', iou: .3 }).pairs.length, 2); });
test('comparison excludes incomplete reference documents', async () => { const p = await demoProject(); const a = await p.snapshot(), b = { ...clone(a), id: 'other', hash: undefined }; delete b.hash; const report = await compareSnapshots(a, b); assert.equal(report.coverage.evaluated.length, 0); assert.equal(report.anchors.f1, null); assert.equal(report.interpretation, 'disagreement-analysis-not-accuracy'); });
test('complete references yield supported metrics, null fields are not negatives', async () => { const p = await demoProject(), doc = p.current.documents[0]; p.record(authoredReference(doc)[0]); p.completeness(doc.id, { families: Object.keys(p.current.schema.families), ranges: [[0, new OffsetMap(doc.text).length]], omissionsChecked: true }); const a = await p.snapshot(); const b = clone(a); delete b.hash; b.id = 'b'; b.records[0].fields.experiencer = 'patient'; const r = await compareSnapshots(a, b, { referenceDeclared: true }); assert.equal(r.anchors.f1, 1); assert.equal(r.fields.experiencer.accuracy, 0); assert.equal(r.evaluatedFieldTuples.f1, 0); });
test('different schemas cannot be compared', async () => { const p = await demoProject(), a = await p.snapshot(); await assert.rejects(compareSnapshots(a, { ...a, schemaHash: 'different' })); });
test('kappa is undefined for empty and constant units', () => { assert.equal(categoricalKappa([], [], ['a', 'b']), null); assert.equal(categoricalKappa(['a'], ['a'], ['a', 'b']), null); assert.equal(categoricalKappa(['a', 'b'], ['a', 'b'], ['a', 'b']), 1); });
test('training export excludes test/protected/demo and partial review', async () => { const doc = await sourceDocument('train-note', new TextEncoder().encode('x'), { split: 'train' }), testdoc = await sourceDocument('test-note', new TextEncoder().encode('x'), { split: 'test' }); const p = await ReviewProject.create([doc, testdoc], DEMO_SCHEMA); const empty = await p.snapshot(); assert.deepEqual(p.trainingCandidates(empty.id), []); for (const d of [doc, testdoc])
    p.completeness(d.id, { families: Object.keys(DEMO_SCHEMA.families), ranges: [[0, 1]], omissionsChecked: true }); const full = await p.snapshot(); assert.deepEqual(p.trainingCandidates(full.id).map(d => d.documentId), ['train-note']); });
test('blind assignments omit predictions and snapshots', async () => { const p = await demoProject(); await p.addRun(await authoredSuggestionRun(p, p.current.documents[0])); const b = await p.blindAssignment('B'); assert.equal(b.current.runs.length, 0); assert.equal(b.current.snapshots.length, 0); assert.equal(b.current.mode, 'blind'); });
test('adjudication keeps both input snapshots', async () => { const a = await demoProject(), s1 = await a.snapshot(), b = await ReviewProject.create(a.current.documents, a.current.schema, { actor: 'B' }), s2 = await b.snapshot(); await a.importSnapshot(s2); const before = a.current.snapshots.map(canonical); const c = await a.adjudicate(s1.id, s2.id, [], { rationale: 'Insufficient evidence' }); assert.equal(c.kind, 'adjudicated'); assert.deepEqual(a.current.snapshots.slice(0, 2).map(canonical), before); });
test('ZIP CRC known answer and unsafe paths', () => { assert.equal(crc32(new TextEncoder().encode('123456789')), 0xcbf43926); for (const path of ['../x', '/x', 'a/../x', 'a\\b', 'a//b', 'a%2fb', 'a:1'])
    assert.throws(() => safePath(path)); });
test('ZIP store round trip and corruption rejection', async () => { const f = new Map([['data.txt', new TextEncoder().encode('abc')]]), bytes = zipStore(f); assert.equal(new TextDecoder().decode((await unzipBounded(bytes)).get('data.txt')), 'abc'); const bad = bytes.slice(); bad[38] ^= 1; await assert.rejects(unzipBounded(bad)); });
test('ZIP limits fail before excessive allocation', async () => { const bytes = zipStore(new Map([['a', new Uint8Array(100)]])); await assert.rejects(unzipBounded(bytes, { archive: 1000, files: 3, total: 10, file: 10 })); });
test('portable native bundle round trips exact text, predictions and frozen layers', async () => { const p = await demoProject(), d = p.current.documents[0], r = await authoredSuggestionRun(p, d); await p.addRun(r); p.review(r.id, r.records[0].id, 'accepted'); await p.snapshot(); const restored = await importBundle(await exportBundle(p)); assert.equal(canonical(restored), canonical(p.current)); });
test('bundle detects malicious manifest/file changes', async () => { const p = await demoProject(), files = await unzipBounded(await exportBundle(p)); files.set('documents/000000.txt', new TextEncoder().encode('changed')); await assert.rejects(importBundle(zipStore(files)), /hash/); });
test('idle/hidden/waiting time is excluded from active time', () => { let t = 0; const timer = new ActiveTimer({ clock: () => t, idleMs: 100 }); t = 80; assert.equal(timer.tick(), 80); t = 200; assert.equal(timer.tick(), 100); timer.touch(); t = 250; timer.pause(true); t = 350; timer.pause(false); timer.touch(); t = 375; timer.visibility(false); t = 500; assert.equal(timer.report().activeMs, 175); });
