import { test } from 'node:test';
import assert from 'node:assert/strict';
import { validateModelManifest, importModelPackage, qualifyForSchema, compareTensors } from '../../src/nextmedtator/model-package.mjs';
import { DEMO_SCHEMA } from '../../src/nextmedtator/contracts.mjs';
import { sha256, canonical, clone, sourceDocument } from '../../src/nextmedtator/integrity.mjs';
import { zipStore } from '../../src/nextmedtator/zip.mjs';
import { demoProject, authoredSuggestionRun } from '../../src/nextmedtator/samples.mjs';
import { machineSnapshot } from '../../src/nextmedtator/project.mjs';
import { compareSnapshots } from '../../src/nextmedtator/compare.mjs';
import { importJSONL, exportMedTator } from '../../src/nextmedtator/interchange.mjs';
const enc = new TextEncoder();
async function fixture() { const graph = new Uint8Array([1, 2, 3]), reference = enc.encode('{"inputs":{},"outputs":{}}'); return { format: 'nextmedtator-model-v1', id: 'test-conformance', version: '0.0.1', runtime: 'onnxruntime-web', runtimeVersion: '1.23.2', lineage: { base: { model: 'synthetic-test-graph-not-gliner', revision: 'a'.repeat(40) } }, license: { id: 'Apache-2.0', notice: 'Synthetic test fixture; not a real model' }, files: [{ path: 'test.onnx', bytes: graph.length, sha256: await sha256(graph), role: 'graph' }, { path: 'reference.json', bytes: reference.length, sha256: await sha256(reference), role: 'fixture' }], variants: [{ id: 'cpu', backend: 'wasm', precision: 'fp32', graph: 'test.onnx', codec: 'tensor-conformance-v1', fixtures: ['reference.json'] }], capabilities: [] }; }
test('model manifest permits pinned baseline and separately identified merged LoRA', async () => { const m = await fixture(); validateModelManifest(m); m.lineage.adapter = { sha256: 'b'.repeat(64), baseRevision: 'a'.repeat(40) }; m.lineage.merge = 'merged-export'; m.lineage.trainedHeads = 'unchanged'; validateModelManifest(m); m.lineage.adapter.baseRevision = 'c'.repeat(40); assert.throws(() => validateModelManifest(m), /base mismatch/); });
test('model manifests reject executable plugins, missing graphs and unknown codecs', async () => { for (const edit of [m => m.files[0].path = 'payload.js', m => m.variants[0].codec = 'downloaded-decoder', m => m.files[0].role = 'executable', m => m.variants[0].graph = 'missing.onnx']) {
    const m = await fixture();
    edit(m);
    assert.throws(() => validateModelManifest(m));
} });
test('model files require exact non-placeholder hashes', async () => { const m = await fixture(); m.files[0].sha256 = '...'; assert.throws(() => validateModelManifest(m)); });
test('package import checks bytes and preserves baseline/adapter provenance', async () => { const m = await fixture(), entries = new Map([['manifest.json', enc.encode(canonical(m))], ['test.onnx', new Uint8Array([1, 2, 3])], ['reference.json', enc.encode('{"inputs":{},"outputs":{}}')]]); const pkg = await importModelPackage(zipStore(entries)); assert.equal(pkg.manifest.lineage.base.model, 'synthetic-test-graph-not-gliner'); entries.set('test.onnx', new Uint8Array([4, 5, 6])); await assert.rejects(() => importModelPackage(zipStore(entries)), /integrity/); });
test('conformance-only package explicitly fails clinical qualification', async () => { const m = await fixture(); assert.throws(() => qualifyForSchema({ manifest: m }, DEMO_SCHEMA), e => e.code === 'CLINICAL_RUNTIME_UNQUALIFIED'); });
test('tensor tolerances are explicit and nonfinite values fail', () => { assert.equal(compareTensors([1], [1.01], { atol: .02 }).pass, true); assert.equal(compareTensors([1], [1.01]).pass, false); assert.throws(() => compareTensors([NaN], [1])); assert.throws(() => compareTensors([1], [1], { atol: -1 })); });
test('machine snapshots reject two runs for the same document', async () => { const p = await demoProject(); const run = await authoredSuggestionRun(p, p.current.documents[0]); await p.addRun(run); await assert.rejects(() => machineSnapshot(p, [run.id, run.id]), /one run per document/); });
test('machine snapshot is not independent and keeps exact source/schema identities', async () => { const p = await demoProject(); const r = await authoredSuggestionRun(p, p.current.documents[0]); await p.addRun(r); const s = await machineSnapshot(p, [r.id]); assert.equal(s.kind, 'machine'); assert.equal(s.independent, false); await p.importSnapshot(s); assert.equal(p.current.snapshots[0].hash, s.hash); });
test('failed machine coverage is excluded, not scored as negative', async () => { const p = await demoProject(), doc = p.current.documents[0]; p.completeness(doc.id, { families: Object.keys(DEMO_SCHEMA.families), ranges: [[0, doc.text.length]], omissionsChecked: true }); const h = await p.snapshot(); const run = await authoredSuggestionRun(p, doc); run.status = 'failed'; run.coverage = []; run.records = []; await p.addRun(run); const m = await machineSnapshot(p, [run.id]); const report = await compareSnapshots(h, m); assert.equal(report.coverage.evaluated.length, 0); assert.equal(report.anchors.f1, null); });
test('JSONL explicit mappings preserve source identifiers locally and reject invalid text', async () => { const p = await importJSONL('{"key":42,"note":"ไทย\\r\\n"}', DEMO_SCHEMA, { idField: 'key', textField: 'note' }); assert.equal(p.current.documents[0].text, 'ไทย\r\n'); assert.equal(p.current.documents[0].provenance.originalId, '42'); await assert.rejects(() => importJSONL('{"id":"a","text":12}', DEMO_SCHEMA)); });
test('XML export preserves CR as a character reference and emits loss report', async () => { const doc = await sourceDocument('xml', enc.encode('a\r\nb')); const result = exportMedTator(doc, [], DEMO_SCHEMA); assert.match(result.xml, /&#13;/); assert.ok(result.losses.length > 0); });
