import {test} from 'node:test';import assert from 'node:assert/strict';
import {demoProject,authoredReference,authoredSuggestionRun} from '../../src/nextmedtator/samples.mjs';
import {machineSnapshot} from '../../src/nextmedtator/project.mjs';
import {compareSnapshots} from '../../src/nextmedtator/compare.mjs';
import {clone,canonical,OffsetMap} from '../../src/nextmedtator/integrity.mjs';
import {exportBundle,importBundle} from '../../src/nextmedtator/bundle.mjs';
import {legacySchema} from '../../src/nextmedtator/assist.mjs';
async function complete(p){for(const d of p.current.documents)p.completeness(d.id,{families:Object.keys(p.current.schema.families),ranges:[[0,new OffsetMap(d.text).length]],omissionsChecked:true,relationsChecked:true});return p.snapshot();}
test('successive undo walks history and stores only changed records',async()=>{const p=await demoProject(),r=authoredReference(p.current.documents[0]);p.record(r[0]);p.record(r[1]);p.undo();assert.equal(p.current.draft.records.length,1);p.undo();assert.equal(p.current.draft.records.length,0);assert.equal(p.current.events[0].details.before,undefined);assert.equal(p.current.events[0].details.undo.records.length,1);});
test('machine snapshot import prevents later false independent labels',async()=>{const donor=await demoProject();await donor.addRun(await authoredSuggestionRun(donor,donor.current.documents[0]));const machine=await machineSnapshot(donor,donor.current.runs.map(r=>r.id));const p=await demoProject();await p.importSnapshot(machine);assert.equal((await p.snapshot()).independent,false);});
test('linked set review preserves prediction IDs and rewrites human relation IDs atomically',async()=>{const p=await demoProject(),doc=p.current.documents[0];const run=await authoredSuggestionRun(p,doc);const ref=authoredReference(doc);run.records=ref;run.records[0].relations=[{type:'related',targetId:run.records[1].id}];await p.addRun(run);p.reviewGroup(run.id,run.records.map(r=>r.id));assert.equal(p.current.draft.records[0].relations[0].targetId,p.current.draft.records[1].id);assert.notEqual(p.current.draft.records[0].id,run.records[0].id);p.undo();assert.equal(p.current.draft.records.length,0);assert.equal(p.current.runs[0].records[0].relations[0].targetId,run.records[1].id);});
test('evidence mismatch changes complete-record metrics without changing anchor metrics',async()=>{const p=await demoProject();p.record(authoredReference(p.current.documents[0])[0]);const a=await complete(p),b=clone(a);delete b.hash;b.id='b';b.records[0].evidence=[{start:0,end:3,text:'Her'}];const report=await compareSnapshots(a,b);assert.equal(report.anchors.f1,1);assert.equal(report.recordCompleteness.f1,0);assert.equal(report.disagreements[0].kind,'evidence-mismatch');});
test('relation scoring requires declared coverage and detects wrong linkage',async()=>{const p=await demoProject(),r=authoredReference(p.current.documents[0]);r[0].relations=[{type:'related',targetId:r[1].id}];p.transformRecords;const data=clone(p.current);data.draft.records=r;const {ReviewProject}=await import('../../src/nextmedtator/project.mjs');const q=await ReviewProject.open(data),a=await complete(q),b=clone(a);delete b.hash;b.id='b';b.records[0].relations=[];const report=await compareSnapshots(a,b);assert.equal(report.relationMetrics.fn,1);assert.equal(report.relationMetrics.f1,0);assert.ok(report.recordCompleteness.f1<1);});
test('comparisons and unresolved adjudication survive native export',async()=>{const p=await demoProject(),a=await complete(p),q=await demoProject();const b=await complete(q);await p.importSnapshot(b);const report=await compareSnapshots(a,b);await p.addComparison(report);const c=await p.adjudicate(a.id,b.id,[],{rationale:'Insufficient evidence',unresolved:['case-1'],reasonCodes:{'case-1':'insufficient-evidence'}});const restored=await importBundle(await exportBundle(p));assert.deepEqual(restored.extensions.comparisons,[report]);assert.deepEqual(c.unresolved,['case-1']);assert.equal(restored.snapshots.at(-1).reasonCodes['case-1'],'insufficient-evidence');});
test('legacy inference schema follows loaded tags and attributes',()=>{const schema=legacySchema({etags:[{name:'DRUG',attrs:[{name:'status',vtype:'list',values:['current','stopped']}]}]});assert.deepEqual(Object.keys(schema.families),['DRUG']);assert.deepEqual(schema.families.DRUG.fields.status.values,['current','stopped']);});

test('document windows and inference duration do not fragment same-configuration machine layers',async()=>{const p=await demoProject();const {makeRun}=await import('../../src/nextmedtator/project.mjs');const ids=[];for(const [i,doc] of p.current.documents.slice(0,2).entries()){const run=await makeRun(p,doc,[],{producer:{kind:'model',name:'baseline'},settings:{threshold:.5},windows:[{from:0,to:i+1}],timing:{inferenceMs:10+i}});await p.addRun(run);ids.push(run.id);}assert.equal((await machineSnapshot(p,ids)).runIds.length,2);});

test('schema migration previews losses and preserves original project as an inspectable revision',async()=>{const {previewSchemaMigration,applySchemaMigration}=await import('../../src/nextmedtator/migration.mjs');const p=await demoProject();p.record(authoredReference(p.current.documents[0])[0]);const schema=clone(p.current.schema);schema.version='2';delete schema.families.condition_occurrence.fields.experiencer;const proposal=await previewSchemaMigration(p,schema);assert.equal(proposal.report.losses[0].field,'experiencer');const next=await applySchemaMigration(p,proposal);assert.equal(next.current.extensions.schemaMigration.priorProject.schemaHash,p.current.schemaHash);assert.notEqual(next.current.schemaHash,p.current.schemaHash);assert.equal(p.current.draft.records[0].fields.experiencer,'family');assert.equal(next.current.draft.records[0].fields.experiencer,undefined);});

test('legacy working copy carries document labels and declared binary relations',async()=>{const {legacyRecords}=await import('../../src/nextmedtator/assist.mjs');const {sourceDocument}=await import('../../src/nextmedtator/integrity.mjs');const schema=legacySchema({etags:[{name:'DRUG',attrs:[]},{name:'CONDITION',attrs:[]},{name:'LABEL',is_non_consuming:true,attrs:[]}],rtags:[{name:'TREATS',attrs:[{name:'from',vtype:'idref'},{name:'to',vtype:'idref'}]}]});const doc=await sourceDocument('d',new TextEncoder().encode('Drug condition'));const records=legacyRecords({tags:[{tag:'DRUG',id:'a',spans:'0~4',text:'Drug'},{tag:'CONDITION',id:'b',spans:'5~14',text:'condition'},{tag:'LABEL',id:'c',spans:'-1~-1',text:''},{tag:'TREATS',id:'r',from:'a',to:'b'}]},doc,schema);assert.deepEqual(records[0].relations,[{type:'TREATS',targetId:'b'}]);assert.deepEqual(records[2].anchor,[]);});

test('adjudication candidate selection copies linked groups without altering input identities',async()=>{const p=await demoProject(),r=authoredReference(p.current.documents[0]);r[0].relations=[{type:'related',targetId:r[1].id}];p.transformRecords([],r);const snapshot=await p.snapshot();p.copyAdjudicationGroup(snapshot.id,r[0].id);const copies=p.current.draft.records.filter(r=>r.origin.kind==='human-adjudication');assert.equal(copies.length,2);assert.equal(copies[0].relations[0].targetId,copies[1].id);assert.equal(p.current.snapshots[0].hash,snapshot.hash);});

test('legacy imported annotations with unknown provenance cannot become an independent reference by freezing',async()=>{const p=await demoProject(),r=authoredReference(p.current.documents[0])[0];r.origin={kind:'imported',reviewStatus:'unknown'};p.transformRecords([],[r]);assert.equal((await p.snapshot()).independent,false);});

test('failed attempts retain comparable settings but exclude their documents from scored negatives',async()=>{const p=await demoProject();const {makeRun}=await import('../../src/nextmedtator/project.mjs');const good=await makeRun(p,p.current.documents[0],[],{producer:{kind:'model',name:'baseline'},settings:{threshold:.5}}),failed=await makeRun(p,p.current.documents[1],[],{producer:{kind:'model',name:'baseline'},settings:{threshold:.5},status:'failed',coverage:[],failures:[{category:'local-runtime-failure'}]});await p.addRun(good);await p.addRun(failed);const machine=await machineSnapshot(p,[good.id,failed.id]);assert.equal(machine.completeness[failed.documentId].full,false);assert.deepEqual(failed.settings,good.settings);const human=await complete(p),report=await compareSnapshots(human,machine);assert.deepEqual(report.coverage.evaluated,[good.documentId]);assert.deepEqual(p.current.runs[1].failures,[{category:'local-runtime-failure'}]);});
